### ISSUE TITLE
Update User list designs

### ISSUE THREAD

**Issue by jde** [coralproject/design#3]
Add the following features to the User List box:
- [ ] a sort feature that allows sorting by the filters that make up the query that produce the list (for the design, use: "# of Comments", "% ModeratorDeleted" and "Reply Ratio")
- [ ] pagination
- [ ] total number of users

Note that updates to the User Card that makes up the User List box are described in #4

**Comment by egrdina** [comment]
@jde regarding the third bullet, the current designs show the total number of users above the list of users, in addition to being in the sentence which shows what filters are applied. Is the third bullet referring to something else?
![screen shot 2016-03-10 at 12 56 48 pm](https://cloud.githubusercontent.com/assets/7856099/13679005/9622bdec-e6bf-11e5-9e18-49d1fc6b262e.png)

**Comment by egrdina** [comment]
![screen shot 2016-03-18 at 2 50 25 pm](https://cloud.githubusercontent.com/assets/7856099/14085218/a116db26-f4ec-11e5-90fa-3134cd315fe4.png)

**Comment by pablocubico** [comment]
Posting this to point out some differences we currently have:
- Collapse menu: The link at the bottom would dissapear when the sidebar gets collapsed, so I left the current "hamburguer" toggle as is.
- Date created / modified: we don't have those, at least, not right now.
- Header top-right icons: I don't know what those icons should do! 
- Language switcher: currently lives on the top-right corner (where the cog wheel is on the new design), what should we do about it?
- What does the list icon on the rightmost side of the table header do?
- Checkboxes: there are no multiple selection actions available so far.

![grouplistui](https://cloud.githubusercontent.com/assets/340766/14110372/78ae06e0-f59c-11e5-9f3b-13e9f1bc798a.JPG)

**Comment by egrdina** [comment]
Thanks @pablocubico Here are some answers to your questions: 
1. Collapsible menu: The idea is, when collapsed, the icons would still be visible. I will execute a design about what the collapsible view looks like. From there, I believe we could get rid of the hamburger menu and keep all menu items contained in the left panel. 
2. Bummer :( @jde is there another metric we want to include aside from Group name and Group description? 
3. The idea behind the top-right icons is they would show who is active on Coral, similar to Google Docs. 
4. Can the language switcher live in the cog? I don't have a good grasp of which/how many settings we will have, so maybe the language is just contained in a tooltip for now? (would give me a nice excuse to get that tooltip style down!)
5. I believe you're referring to the individual people shown. Is it possible to show 3 of individuals on the Coral Project and then truncate and say "+X amount more"? 
6. I deleted the check boxes for now. The idea is a user would be able to select more than one group for once. A feature we can table for now, but one I think might be valuable later.

**Comment by pablocubico** [comment]
Hey @egrdina, about **5**, I meant this icon:

![icon](https://cloud.githubusercontent.com/assets/340766/14212101/abb65ade-f807-11e5-805e-95be0a60075d.JPG)

Is it a list view / grid view switch?

**Comment by egrdina** [comment]
ahh @pablocubico I had the icon wrong. Here is an updated screenshot. The idea behind that icon is that a user could switch between a list view and a card view. So the updated screenshot shows the icon as grids bc if a user clicked it, the lists would turn into cards. 

I'd be ok leaving it off for now since we don't yet have card-view designs. Also, if the icon causes confusion for others, we might want to revisit it altogether. 

<img width="738" alt="screen shot 2016-03-31 at 10 55 44 am" src="https://cloud.githubusercontent.com/assets/7856099/14212182/9d2229ec-f7ff-11e5-863c-fd508b42db2f.png">

**Comment by pablocubico** [comment]
Great, I was just confused bc I thought we were ditching the grid view. We can leave it off for this iteration.

**Comment by egrdina** [comment]
Here is what the collapsed menu should look like. 

<img width="152" alt="screen shot 2016-04-01 at 1 36 51 pm" src="https://cloud.githubusercontent.com/assets/7856099/14215103/e8ec01a4-f80e-11e5-9615-253ce9684d50.png">  

The User list would expand in width (filters should stay relatively the same since it's such a complex interface to begin with) which would give us the option of including more stats on this page. 
<img width="761" alt="screen shot 2016-04-01 at 1 38 20 pm" src="https://cloud.githubusercontent.com/assets/7856099/14215137/139daed4-f80f-11e5-80d8-646390431ffd.png">
